### ISSUE TITLE
Submarines

### ISSUE THREAD

**Issue by funions123** [oumajgad/BlackICE#27]
Am I doing something wrong or are submarines basically useless?
I have played several games and found that naval bombers and flying boats evaporate convoys while being untouchable by escorts (enemy planes can ward them off though). Meanwhile, having anywhere between 20-50 submarines in single-ship groups roaming the same convoy routes produces ZERO sunk convoys and several dead subs.
I think I sank maybe 3 convoys total with the entire starting german sub fleet, while 9 naval bombers and 12 flying boats have sunk hundreds of convoys flying out of brest.

In a similar vein, having naval bombers and flying boats on naval strike doesn't seem to really do anything either. If I try to throw a ball of planes at a known fleet the stacking penalty removes their ability to do any damage, and if I engage with 3-wing groups at a time it does only superficial damage then the enemy fleet fucks off. Port strikes however do very respectable damage and a sustained port strike campaign can easily put a huge dent in the british navy. 

Playing 11.2.1, not obvious what version this repo is on.

**Comment by DasGleiche** [comment]
In 11.2.1, my convoy raiding as Germany with single subs etc was so effective it brought the UK to surrender without needing to set foot on the British Isles. So no, they are very good and you are simply using them wrong. Convoy routes aren't consistent - they do change, but with enough coverage you should be able to catch them in large numbers. I base subs all around the world before the war in order to maximise their efficacy.

As for NAVs, it does take a few techs before they start really hammering fleets in transit, but once you get to that point they are very effective.

**Comment by Dsafe1** [comment]
> Playing 11.2.1, not obvious what version this repo is on.
There is no dev branch, so master is always the latest wip state. Bigger features or reworks get their own branch.
Old versions are tagged.

**Comment by funions123** [comment]
Were you using 1939-1940 tech SS? I have mine on passive as well, does that impact their spotting? I had my SS and CSS raiding the same rough area as my flying boats. I also tried using some 1941 tech SS to raid the uk convoys in the atlanic and all of them died without sinking anything.

As for the surrender limit, my UK basically nullified the impact of convoy raiding despite taking massive damage (20000 ic of convoys, 3 million tons of cargo from september 1940 to august 1941) by escorting them. They are at 98% surrender limit.

![image](https://github.com/oumajgad/BlackICE/assets/39248127/638112a2-4ce9-41c3-8302-914e31db5dbc)

**Comment by DasGleiche** [comment]
I built a number of subs of each model and kept techs up to date. 

I dunno, even as Italy I've had great success with them. So to reanswer your initial question - no, they're not useless.
